name: SabiasQue

options:
  bundleIdPrefix: com.ejemplo

targets:
  SabiasQue:
    type: application
    platform: iOS
    deploymentTarget: "13.0"
    sources:
      - path: Sources
      - path: Resources
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.ejemplo.SabiasQue
        INFOPLIST_FILE: Sources/Info.plist
        # En CI es mejor dejar el icono sin exigir un Asset Catalog:
        ASSETCATALOG_COMPILER_APPICON_NAME: ""
